### ISSUE TITLE
Cannot use object of type Zxing\Qrcode\Decoder\ECBlocks as array

### ISSUE THREAD

**Issue by ThomasLandauer** [endroid/QrCode#100] opened 2017-04-23 14:12 UTC
When I do this:
````
<img src="{{ qrcode_data_uri('Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.') }}" />
````
... I get
````
Cannot use object of type Zxing\Qrcode\Decoder\ECBlocks as array
````
... with a reference to ` vendor\khanamiryan\qrcode-detector-decoder\lib\qrcode\decoder\Version.php at line 96`:
````
return $this->ecBlocks[$ecLevel->getOrdinal()];
````
Is there some sort of hard limit for string length around 300-400 chars? Or is it dependent from the size of the QR code? Please explain this somewhere and/or catch the error before khanamiryan/qrcode-detector-decoder receives it.

**Comment by endroid** [comment] 2017-04-23 21:18
Hi @ThomasLandauer here the URI is generated and readable without any issues when I insert your code fragment in a template. So I think this is not caused only by the length of the contents. Please create a failing test case so I can see if I can create a workaround.

**Comment by ThomasLandauer** [comment] 2017-04-23 22:13
Sorry, I'm not sure where/how to create an appropriate test :-(

I just found out that it depends on the `size` setting (in your `config.yml`). So try this:
````
<img src="{{ qrcode_data_uri('Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.', {'size':200}) }}" />
````
- At size=100 I get what you (probably) intended: `Adjust your parameters to increase readability or disable built-in validation.`

- At size=200 I get the `Zxing\Qrcode\Decoder\ECBlocks` message from above.

- At size=600 I get `Adjust your parameters...` again!

- And at size=1500 I get `OutOfMemoryException` :-)

**Comment by endroid** [comment] 2017-04-25 11:50
Thank you, will check again later.

**Comment by endroid** [comment] 2017-06-18 15:29
Hi @ThomasLandauer, here I also get the "Adjust your parameters" message you mentioned for sizes 100 and 600. However, when I generate an 1000 pixel image it validates or when I use my Android barcode scanner for the 600 pixel image I am able to read the result, so here the built-in validator is somewhat stricter than my own.

About the memory consumption: when I generate a 2500 pixel image, it validates, but this takes about 100MB to generate without validation and 350MB with validation. I also checked a 1000 pixel image and here it took 10MB to generate without validation and 100MB with validation, a tenfold increase. So I will add a warning in the readme about this big performance hit.

If you have issues with this strictness or memory consumption, please create an issue in the  https://github.com/khanamiryan/php-qrcode-detector-decoder library so the maintainer can look at it. I don't get an error at size 200 so I am not able to reproduce that issue (maybe it is fixed in the latest version) but this is clearly an issue in the validator library so if it still occurs you can also mention that there.

**Closed by endroid** 2017-06-18 15:29 UTC
Labels: question, unable to reproduce
