### ISSUE TITLE
Call to undefined function Endroid\QrCode\imagettfbbox() in PHP7 with php7.0-gd installed

### ISSUE THREAD

**Issue by alexmatveev** [endroid/QrCode#38] opened 2016-03-25 08:32 UTC
Fatal error: 
500 Internal Server Error - FatalThrowableError
in vendor/endroid/qrcode/src/QrCode.php at line 1200

**Comment by endroid** [comment] 2016-03-26 19:22
Hi @alexmatveev I can not reproduce your problem (also working on PHP7 here) so I will close this issue but I read around the Internet that this could be caused by a missing FreeType library. So you could try installing that library and see if your problem is solved. Please let me know if you find a solution...

**Closed by endroid** 2016-03-26 19:22 UTC

**Comment by endroid** [comment] 2016-03-26 19:38
I also added a function_exists check and a hint for installing the FreeType library in 1.6.1 as this seems to be a solution to some people.

**Comment by alexmatveev** [comment] 2016-03-26 19:48
@endroid I fixed up my problem with installing PHP from aptitude, instead of manually building, because there were no time to research. Thanks for response.

**Comment by marciomrs4** [comment] 2016-07-24 21:55
After install php7.0-gd using apttitude, you must to restart apache2.
