### ISSUE TITLE
Not rendering with 'errorCorrection' => \Endroid\QrCode\QrCode::LEVEL_MEDIUM

### ISSUE THREAD

**Issue by dalpras** [endroid/QrCode#49] opened 2016-06-09 12:05 UTC
If you try to render an *http address* with these params:

	$defaultOptions = [
		'text'            => 'http://www.example.com/it/it/contact/qr/hit/id/1	',
		'ext'             => 'png',
		'size'            => 300,
		'padding'         => 10,
		'destDir'         => APPLICATION_PATH . "/../public/cache/qrcode",
		'backgroundColor' => [
			'r' => 255,
			'g' => 255,
			'b' => 255,
			'a' => 0],
		'foregroundColor' => [
			'r' => 0,
			'g' => 0,
			'b' => 0,
			'a' => 0],
		'errorCorrection' => \Endroid\QrCode\QrCode::LEVEL_MEDIUM,
	];

it will thow an Exception: 
`Undefined offset: 43 in /var/www/vhosts/vimarcom/webroot/vendor/endroid/qrcode/src/QrCode.php on line 1150.`

It works fine with other ERROR LEVELS.

**Comment by endroid** [comment] 2016-06-21 12:40
Hi @dalpras I am not familiar with this part of the code as this was adapted from the original script by Mr Swetake to create this library. However maybe you can try and see if this issue also occurs on one of the earlier versions of this library to see if it didnt work from the beginning or it was broken by a later commit. In the latter case we can probably fix this by looking at the commit history.

**Comment by dalpras** [comment] 2016-06-29 08:56
Hi endroid, the master version I was using in 02/2015 was not affected by this bug. 
Sorry I dont have time to investigate.

**Comment by endroid** [comment] 2016-07-26 09:03
Hi @dalpras. I wrote a test for the use case you described but it does not fail on my side. Please check your code to see what parameters are set other than the ones you mentioned above so we can confirm the error and create a failing test case we can fix.

https://github.com/endroid/QrCode/commit/58e7d55a3ca3277bbf283eb31aad19befc59a473

**Comment by endroid** [comment] 2016-09-02 19:45
Hi @dalpras please feel free to reopen this issue once you have committed a failing test. I'm closing it for now because for now it cannot be reproduced on my side.

**Closed by endroid** 2016-09-02 19:45 UTC
Labels: invalid
